export type MoveButton = "attack" | "special";
export type MoveDirection = "neutral" | "forward" | "back" | "up" | "down";
export type MoveContext = "ground" | "air";
export type MoveRole =
  | "quick-poke"
  | "long-poke"
  | "quick-pop-up"
  | "heavy-pop-up"
  | "close-low"
  | "air-poke"
  | "air-control"
  | "placeholder";

export type MoveDefinition = {
  id: string;
  button: MoveButton;
  direction: MoveDirection;
  context: MoveContext;
  smash?: boolean;
  role: MoveRole;
  startupFrames: number;
  activeFrames: number;
  recoveryFrames: number;
  damage: number;
  knockback: { x: number; y: number };
  hitbox: { x: number; y: number; width: number; height: number };
  shieldDamage: number;
  hitstopFrames: number;
  movementMultiplier?: number;
  selfVelocity?: { x: number; y: number };
  cooldownKey?: string;
};

export const moveDefinitions: Record<string, MoveDefinition> = {
  jab: {
    id: "jab",
    button: "attack",
    direction: "neutral",
    context: "ground",
    role: "quick-poke",
    startupFrames: 5,
    activeFrames: 4,
    recoveryFrames: 12,
    damage: 6,
    knockback: { x: 320, y: -80 },
    hitbox: { x: 24, y: -78, width: 38, height: 24 },
    shieldDamage: 12,
    hitstopFrames: 4,
    movementMultiplier: 0.45,
  },
  forwardTilt: {
    id: "forwardTilt",
    button: "attack",
    direction: "forward",
    context: "ground",
    role: "long-poke",
    startupFrames: 7,
    activeFrames: 4,
    recoveryFrames: 14,
    damage: 8,
    knockback: { x: 390, y: -70 },
    hitbox: { x: 28, y: -76, width: 48, height: 24 },
    shieldDamage: 15,
    hitstopFrames: 5,
    movementMultiplier: 0.4,
  },
  upTilt: {
    id: "upTilt",
    button: "attack",
    direction: "up",
    context: "ground",
    role: "quick-pop-up",
    startupFrames: 6,
    activeFrames: 5,
    recoveryFrames: 15,
    damage: 7,
    knockback: { x: 120, y: -455 },
    hitbox: { x: -14, y: -124, width: 44, height: 48 },
    shieldDamage: 14,
    hitstopFrames: 5,
    movementMultiplier: 0.5,
  },
  downTilt: {
    id: "downTilt",
    button: "attack",
    direction: "down",
    context: "ground",
    role: "close-low",
    startupFrames: 6,
    activeFrames: 4,
    recoveryFrames: 13,
    damage: 6,
    knockback: { x: 260, y: 160 },
    hitbox: { x: 18, y: -38, width: 42, height: 26 },
    shieldDamage: 13,
    hitstopFrames: 4,
    movementMultiplier: 0.45,
  },
  forwardSmash: {
    id: "forwardSmash",
    button: "attack",
    direction: "forward",
    context: "ground",
    smash: true,
    role: "long-poke",
    startupFrames: 12,
    activeFrames: 5,
    recoveryFrames: 24,
    damage: 14,
    knockback: { x: 640, y: -130 },
    hitbox: { x: 30, y: -64, width: 72, height: 32 },
    shieldDamage: 24,
    hitstopFrames: 8,
    movementMultiplier: 0.25,
  },
  upSmash: {
    id: "upSmash",
    button: "attack",
    direction: "up",
    context: "ground",
    smash: true,
    role: "heavy-pop-up",
    startupFrames: 11,
    activeFrames: 6,
    recoveryFrames: 25,
    damage: 13,
    knockback: { x: 120, y: -700 },
    hitbox: { x: -18, y: -136, width: 56, height: 62 },
    shieldDamage: 22,
    hitstopFrames: 8,
    movementMultiplier: 0.25,
  },
  downSmash: {
    id: "downSmash",
    button: "attack",
    direction: "down",
    context: "ground",
    smash: true,
    role: "close-low",
    startupFrames: 10,
    activeFrames: 6,
    recoveryFrames: 23,
    damage: 12,
    knockback: { x: 520, y: 240 },
    hitbox: { x: -38, y: -34, width: 96, height: 32 },
    shieldDamage: 22,
    hitstopFrames: 8,
    movementMultiplier: 0.25,
  },
  neutralSpecial: {
    id: "neutralSpecial",
    button: "special",
    direction: "neutral",
    context: "ground",
    role: "long-poke",
    startupFrames: 8,
    activeFrames: 5,
    recoveryFrames: 18,
    damage: 9,
    knockback: { x: 440, y: -110 },
    hitbox: { x: 22, y: -58, width: 54, height: 28 },
    shieldDamage: 18,
    hitstopFrames: 6,
    movementMultiplier: 0.35,
  },
  sideSpecial: {
    id: "sideSpecial",
    button: "special",
    direction: "forward",
    context: "ground",
    role: "long-poke",
    startupFrames: 10,
    activeFrames: 5,
    recoveryFrames: 20,
    damage: 11,
    knockback: { x: 560, y: -120 },
    hitbox: { x: 30, y: -62, width: 66, height: 30 },
    shieldDamage: 22,
    hitstopFrames: 7,
    movementMultiplier: 0.28,
  },
  upSpecial: {
    id: "upSpecial",
    button: "special",
    direction: "up",
    context: "ground",
    role: "heavy-pop-up",
    startupFrames: 10,
    activeFrames: 6,
    recoveryFrames: 22,
    damage: 10,
    knockback: { x: 120, y: -610 },
    hitbox: { x: -16, y: -132, width: 50, height: 58 },
    shieldDamage: 20,
    hitstopFrames: 7,
    movementMultiplier: 0.3,
    selfVelocity: { x: 0, y: -860 },
    cooldownKey: "upSpecial",
  },
  downSpecial: {
    id: "downSpecial",
    button: "special",
    direction: "down",
    context: "ground",
    role: "close-low",
    startupFrames: 9,
    activeFrames: 5,
    recoveryFrames: 18,
    damage: 9,
    knockback: { x: 360, y: 220 },
    hitbox: { x: 16, y: -32, width: 58, height: 30 },
    shieldDamage: 19,
    hitstopFrames: 6,
    movementMultiplier: 0.35,
  },
  neutralAir: {
    id: "neutralAir",
    button: "attack",
    direction: "neutral",
    context: "air",
    role: "air-poke",
    startupFrames: 5,
    activeFrames: 5,
    recoveryFrames: 14,
    damage: 6,
    knockback: { x: 270, y: -80 },
    hitbox: { x: -23, y: -76, width: 46, height: 34 },
    shieldDamage: 12,
    hitstopFrames: 4,
    movementMultiplier: 0.72,
  },
  forwardAir: {
    id: "forwardAir",
    button: "attack",
    direction: "forward",
    context: "air",
    role: "air-control",
    startupFrames: 7,
    activeFrames: 5,
    recoveryFrames: 16,
    damage: 7,
    knockback: { x: 360, y: -80 },
    hitbox: { x: 26, y: -72, width: 54, height: 30 },
    shieldDamage: 14,
    hitstopFrames: 5,
    movementMultiplier: 0.65,
  },
  backAir: {
    id: "backAir",
    button: "attack",
    direction: "back",
    context: "air",
    role: "air-control",
    startupFrames: 7,
    activeFrames: 5,
    recoveryFrames: 16,
    damage: 7,
    knockback: { x: 330, y: -110 },
    hitbox: { x: -70, y: -72, width: 50, height: 30 },
    shieldDamage: 14,
    hitstopFrames: 5,
    movementMultiplier: 0.65,
  },
  upAir: {
    id: "upAir",
    button: "attack",
    direction: "up",
    context: "air",
    role: "quick-pop-up",
    startupFrames: 6,
    activeFrames: 5,
    recoveryFrames: 17,
    damage: 7,
    knockback: { x: 90, y: -420 },
    hitbox: { x: -14, y: -120, width: 44, height: 48 },
    shieldDamage: 14,
    hitstopFrames: 5,
    movementMultiplier: 0.7,
  },
  downAir: {
    id: "downAir",
    button: "attack",
    direction: "down",
    context: "air",
    role: "air-control",
    startupFrames: 7,
    activeFrames: 5,
    recoveryFrames: 18,
    damage: 7,
    knockback: { x: 180, y: 310 },
    hitbox: { x: 0, y: -40, width: 42, height: 44 },
    shieldDamage: 14,
    hitstopFrames: 5,
    movementMultiplier: 0.62,
  },
  airNeutralSpecial: {
    id: "airNeutralSpecial",
    button: "special",
    direction: "neutral",
    context: "air",
    role: "air-poke",
    startupFrames: 9,
    activeFrames: 6,
    recoveryFrames: 22,
    damage: 10,
    knockback: { x: 430, y: -120 },
    hitbox: { x: -31, y: -70, width: 62, height: 36 },
    shieldDamage: 20,
    hitstopFrames: 6,
    movementMultiplier: 0.5,
  },
  airSideSpecial: {
    id: "airSideSpecial",
    button: "special",
    direction: "forward",
    context: "air",
    role: "air-control",
    startupFrames: 11,
    activeFrames: 6,
    recoveryFrames: 24,
    damage: 11,
    knockback: { x: 540, y: -130 },
    hitbox: { x: 30, y: -66, width: 68, height: 34 },
    shieldDamage: 22,
    hitstopFrames: 7,
    movementMultiplier: 0.45,
  },
  airUpSpecial: {
    id: "airUpSpecial",
    button: "special",
    direction: "up",
    context: "air",
    role: "heavy-pop-up",
    startupFrames: 10,
    activeFrames: 6,
    recoveryFrames: 24,
    damage: 10,
    knockback: { x: 90, y: -560 },
    hitbox: { x: -18, y: -132, width: 54, height: 58 },
    shieldDamage: 20,
    hitstopFrames: 7,
    movementMultiplier: 0.48,
    selfVelocity: { x: 0, y: -860 },
    cooldownKey: "upSpecial",
  },
  airDownSpecial: {
    id: "airDownSpecial",
    button: "special",
    direction: "down",
    context: "air",
    role: "air-control",
    startupFrames: 12,
    activeFrames: 6,
    recoveryFrames: 26,
    damage: 11,
    knockback: { x: 220, y: 460 },
    hitbox: { x: -4, y: -36, width: 54, height: 48 },
    shieldDamage: 22,
    hitstopFrames: 7,
    movementMultiplier: 0.42,
  },
};
